baseURL = "/"
languageCode = 'es-AR'
title = 'Vendemos cosas'
theme = "hugo-creative-portfolio-theme"

[params]
  style = "sea"
  description = "Se terminó el acopio"
  copyright = "&copy;2021 Sergio Schvezov"
  email = "sergiusens@gmail.com"

  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [params.social]
  facebook      = "https://facebook.com/sergioschvezov"
  email         = "sergiusens@gmail.com"
  twitter       = "https://twitter.com/sergiusens"
  instagram     = "https://instagram.com/sergiusens"
  whatsapp      = "https://wa.me/543516602709"